"""empty message

Revision ID: be204dbc168c
Revises: d38353986bea
Create Date: 2021-12-10 11:12:55.665597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be204dbc168c'
down_revision = 'd38353986bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'contribute', 'user', ['contributor'], ['username'], onupdate='CASCADE')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'contribute', type_='foreignkey')
    # ### end Alembic commands ###
